# Generated by Django 5.1.1 on 2024-12-03 03:57

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoAcademicoSofia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoAsistencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_asistencia', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Fichas',
            fields=[
                ('numero', models.CharField(max_length=300, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Jornadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_jornada', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Programas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_programa', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Aprendices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=90)),
                ('apellidos', models.CharField(max_length=90)),
                ('tipo_documento', models.CharField(max_length=20)),
                ('no_documento', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=50)),
                ('telefono', models.CharField(max_length=15)),
                ('estado_academico_sofia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SMGDP.estadoacademicosofia')),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SMGDP.fichas')),
            ],
        ),
        migrations.AddField(
            model_name='fichas',
            name='jornada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SMGDP.jornadas'),
        ),
        migrations.AddField(
            model_name='fichas',
            name='programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SMGDP.programas'),
        ),
        migrations.CreateModel(
            name='Quejas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regional', models.CharField(max_length=80)),
                ('motivo', models.CharField(max_length=80)),
                ('centro_formacion', models.CharField(max_length=80)),
                ('nivel_formacion', models.CharField(max_length=80)),
                ('fecha_registro', models.DateField()),
                ('observacion_instructor', models.TextField()),
                ('situacion_riesgo', models.CharField(max_length=100)),
                ('causas_origen_riesgo', models.CharField(max_length=100)),
                ('escalo_riesgo', models.CharField(max_length=80)),
                ('a_quien_escalo', models.CharField(max_length=80)),
                ('acciones_ruta_apren', models.CharField(max_length=100)),
                ('estado_contrato_aprendizaje', models.BooleanField()),
                ('correo_vocero', models.EmailField(max_length=100)),
                ('aprendiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SMGDP.aprendices')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SMGDP.programas')),
            ],
        ),
        migrations.CreateModel(
            name='ObservacionBienestar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacion', models.TextField()),
                ('queja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SMGDP.quejas')),
            ],
        ),
        migrations.CreateModel(
            name='NovedadComite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acta', models.CharField(max_length=80)),
                ('novedad', models.CharField(max_length=80)),
                ('queja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SMGDP.quejas')),
            ],
        ),
        migrations.CreateModel(
            name='EvidenciaQueja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.BinaryField()),
                ('queja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SMGDP.quejas')),
            ],
        ),
        migrations.CreateModel(
            name='Trimestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_trimestre', models.CharField(max_length=80)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SMGDP.fichas')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('documento', models.BigIntegerField(unique=True)),
                ('rol', models.CharField(max_length=80)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UnidadProgramacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidad_programacion', models.CharField(max_length=200)),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SMGDP.fichas')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='quejas',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ObservacionesExtraQuejas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacion', models.TextField()),
                ('imagen', models.BinaryField()),
                ('queja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SMGDP.quejas')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.CharField(max_length=255)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('leido', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Asistencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('observaciones', models.TextField()),
                ('aprendiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SMGDP.aprendices')),
                ('estado_asistencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SMGDP.estadoasistencias')),
                ('unidad_programacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SMGDP.unidadprogramacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
